input_size: 100
hidden_size: 128
num_layers: 2
num_classes: 3
onnx_path: ../../triton/model_repository/topic_definition/1/model.onnx
model_local_path: ../../models
save_top_k: 5
every_n_epochs: 1

#label: LSTM
label: CNN_BILSTM
