FROM python:3.10-slim

WORKDIR /triton

RUN pip install --no-cache-dir \
    "tritonclient[http]" \
    fastapi \
    uvicorn \
    numpy \
    pandas \
    python-multipart \
    nltk \
    pydantic \
    scikit-learn

RUN python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab')"

COPY . .

EXPOSE 8080

CMD ["uvicorn", "web_app:app", "--host", "0.0.0.0", "--port", "8080"]
